"""Network traffic monitoring module for HexWarden.

Not yet implemented. Will capture and analyze network traffic (via scapy)
generated by firmware running in an emulator/sandbox, flagging beaconing
behavior, hardcoded C2 endpoints, and unexpected outbound connections.
Scaffolded now to establish the package structure and the shared
`analyze()` interface contract; the capture/analysis logic lands in a
follow-up change.

Inputs:
    filepath (str): Path to a pcap capture file to analyze.

Outputs:
    List[Finding]: Analysis findings (currently always raises
    AnalysisError until this module is implemented).
"""

from pathlib import Path
from typing import List

from core import AnalysisError, Finding

MODULE_NAME = "network_monitor"


def analyze(filepath: str) -> List[Finding]:
    """Analyze a network capture for suspicious traffic (not yet implemented).

    Args:
        filepath: Absolute or relative path to a pcap capture file.

    Returns:
        List of Finding objects.

    Raises:
        FileNotFoundError: If the capture file does not exist.
        AnalysisError: Always, until this module is implemented.
    """
    path = Path(filepath)
    if not path.is_file():
        raise FileNotFoundError(f"Capture file not found: {filepath}")

    raise AnalysisError(f"Module '{MODULE_NAME}' is not implemented yet.")
